name: Install dependencies & build packages
runs:
  using: "composite"
  steps:
    - name: Install Node
      uses: actions/setup-node@v6.0.0
      with:
        cache: npm
        node-version: 22

    - name: Install npm 11
      shell: bash
      run: npm install -g npm@11

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Build
      shell: bash
      run: npm run build
